# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-dotnet-core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./src
      run: |
        for proj in $(find . -name "*.csproj" -not -name "*FiveM*"); do
          dotnet restore "$proj"
        done
    - name: Build
      working-directory: ./src
      run: |
        for proj in $(find . -name "*.csproj" -not -name "*FiveM*"); do
          dotnet build "$proj" --no-restore
        done
    - name: Test
      working-directory: ./src
      run: |
        for proj in $(find . -name "*.csproj" -not -name "*FiveM*"); do
          dotnet test "$proj" --no-build --verbosity normal
        done